src/apps/account/urls.py
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login_view, name='login'),
    path('charge/', views.charge, name='charge'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('settings/', views.settings, name='settings'),
    path('profile/', views.profile, name='profile'),
    path('login/sso/', views.login_sso, name='login-sso'),
    path('sign-up/', views.signup_view, name='sign-up'),
    path('logout/', views.logout_view, name='logout'),
]

src/apps/television/urls.py
from django.urls import path
from . import views

app_name = 'television'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/video', views.video, name='video'),
]

src/config/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.home.views import index

from config.apis import api

urlpatterns = [
    path('', index, name='index'),
    path('api/', api.urls),
    path('accounts/', include('apps.account.urls')),
    path('demo/', include('apps.demo.urls')),
    path('home/', include('apps.home.urls')),
    path('tv/', include('apps.television.urls')),

    # DjangoStarter
    path('django-starter/', include('django_starter.urls')),

    # 管理后台
    path('admin/', include('django_starter.contrib.admin.urls')),  # 实现 admin 登录验证码
    path('admin/', admin.site.urls),

    # 验证码
    path('captcha/', include('captcha.urls')),
]

src/templates/components/alert.html
{% if message.tags == 'error' %}
    <div class="flex items-center gap-2 p-4 mb-4 text-sm text-red-800 border border-red-300 rounded-lg bg-red-50 dark:bg-gray-800 dark:text-red-400 dark:border-red-800"
         role="alert">
        <i class="fa-solid fa-circle-info flex-shrink-0 inline text-xl"></i>
        <span class="sr-only">Info</span>
        <div>{{ message|safe }}</div>
    </div>
{% elif message.tags == 'info' %}
    <div class="flex items-center gap-2 p-4 mb-4 text-sm text-blue-800 border border-blue-300 rounded-lg bg-blue-50 dark:bg-gray-800 dark:text-blue-400 dark:border-blue-800"
         role="alert">
        <i class="fa-solid fa-circle-info flex-shrink-0 inline text-xl"></i>
        <span class="sr-only">Info</span>
        <div>{{ message|safe }}</div>
    </div>
{% elif message.tags == 'success' %}
    <div class="flex items-center gap-2 p-4 mb-4 text-sm text-green-800 border border-green-300 rounded-lg bg-green-50 dark:bg-gray-800 dark:text-green-400 dark:border-green-800"
         role="alert">
        <i class="fa-solid fa-circle-info flex-shrink-0 inline text-xl"></i>
        <span class="sr-only">Info</span>
        <div>{{ message|safe }}</div>
    </div>
{% elif message.tags == 'warning' %}
    <div class="flex items-center gap-2 p-4 mb-4 text-sm text-yellow-800 border border-yellow-300 rounded-lg bg-yellow-50 dark:bg-gray-800 dark:text-yellow-300 dark:border-yellow-800"
         role="alert">
        <i class="fa-solid fa-circle-info flex-shrink-0 inline text-xl"></i>
        <span class="sr-only">Info</span>
        <div>{{ message|safe }}</div>
    </div>
{% else %}
    <div class="flex items-center gap-2 p-4 text-sm text-gray-800 border border-gray-300 rounded-lg bg-gray-50 dark:bg-gray-800 dark:text-gray-300 dark:border-gray-600"
         role="alert">
        <i class="fa-solid fa-circle-info flex-shrink-0 inline text-xl"></i>
        <span class="sr-only">Info</span>
        <div>{{ message|safe }}</div>
    </div>
{% endif %}

src/templates/components/footer.html
<footer class="bg-white dark:bg-gray-900">
    <div class="mx-auto w-full container p-4 py-6 lg:py-8">
        <div class="md:flex md:justify-between">
            <div class="mb-6 md:mb-0">
                <a href="{% url 'index' %}" class="flex gap-2 items-center">
                    <i class="fa-solid fa-tv text-blue-500 text-2xl"></i>
                    <span class="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">Today TV</span>
                </a>
            </div>
            <div class="grid grid-cols-2 gap-8 sm:gap-6 sm:grid-cols-3">
                <div>
                    <h2 class="mb-6 text-sm font-semibold text-gray-900 uppercase dark:text-white">Resources</h2>
                    <ul class="text-gray-500 dark:text-gray-400 font-medium">
                        <li class="mb-4">
                            <a href="https://deali.cn/" class="hover:underline" target="_blank">CodeLab</a>
                        </li>
                        <li>
                            <a href="http://blog.deali.cn/" class="hover:underline" target="_blank">StarBlog</a>
                        </li>
                    </ul>
                </div>
                <div>
                    <h2 class="mb-6 text-sm font-semibold text-gray-900 uppercase dark:text-white">Follow us</h2>
                    <ul class="text-gray-500 dark:text-gray-400 font-medium">
                        <li class="mb-4">
                            <a href="https://github.com/deali-Axy/" class="hover:underline" target="_blank">Github</a>
                        </li>
                        <li>
                            <a href="https://discord.gg/4eeurUVvTy" class="hover:underline">Discord</a>
                        </li>
                    </ul>
                </div>
                <div>
                    <h2 class="mb-6 text-sm font-semibold text-gray-900 uppercase dark:text-white">Legal</h2>
                    <ul class="text-gray-500 dark:text-gray-400 font-medium">
                        <li class="mb-4">
                            <a href="#" class="hover:underline">Privacy Policy</a>
                        </li>
                        <li>
                            <a href="#" class="hover:underline">Terms &amp; Conditions</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <hr class="my-6 border-gray-200 sm:mx-auto dark:border-gray-700 lg:my-8"/>
        <div class="sm:flex sm:items-center sm:justify-between">
          <span class="text-sm text-gray-500 sm:text-center dark:text-gray-400">
              © 2024 <a href="https://deali.cn/" class="hover:underline">CodeLab™</a>. All Rights Reserved.
          </span>
            <div class="flex mt-4 sm:justify-center sm:mt-0">
                <a href="#" class="text-gray-500 hover:text-gray-900 dark:hover:text-white">
                    <i class="fa-brands fa-facebook-f"></i>
                    <span class="sr-only">Facebook page</span>
                </a>
                <a href="#" class="text-gray-500 hover:text-gray-900 dark:hover:text-white ms-5">
                    <i class="fa-brands fa-discord"></i>
                    <span class="sr-only">Discord community</span>
                </a>
                <a href="#" class="text-gray-500 hover:text-gray-900 dark:hover:text-white ms-5">
                    <i class="fa-brands fa-twitter"></i>
                    <span class="sr-only">Twitter page</span>
                </a>
                <a href="#" class="text-gray-500 hover:text-gray-900 dark:hover:text-white ms-5">
                    <i class="fa-brands fa-github"></i>
                    <span class="sr-only">GitHub account</span>
                </a>
                <a href="#" class="text-gray-500 hover:text-gray-900 dark:hover:text-white ms-5">
                    <i class="fa-brands fa-dribbble"></i>
                    <span class="sr-only">Dribbble account</span>
                </a>
            </div>
        </div>
    </div>
</footer>

src/templates/components/header.html
<nav class="bg-white border-gray-200 dark:bg-gray-900 dark:border-gray-700">
    <div class="container flex flex-wrap items-center justify-between mx-auto px-4 py-4 lg:px-0">
        <a href="{% url 'index' %}" class="flex items-center text-2xl space-x-3 rtl:space-x-reverse">
            <i class="fa-solid fa-tv text-transparent bg-clip-text bg-gradient-to-r from-blue-500 to-red-600"></i>
            <span class="self-center font-semibold whitespace-nowrap dark:text-white">Today TV</span>
        </a>
        <button data-collapse-toggle="navbar-multi-level" type="button"
                class="inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600"
                aria-controls="navbar-multi-level" aria-expanded="false">
            <span class="sr-only">打开主菜单</span>
            <i class="fa-solid fa-bars"></i>
        </button>
        <div class="hidden w-full md:block md:w-auto" id="navbar-multi-level">
            <ul class="flex flex-col font-medium p-4 md:p-0 mt-4 border border-gray-100 rounded-lg bg-gray-50 md:space-x-8 rtl:space-x-reverse md:flex-row md:mt-0 md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
                <li>
                    <a href="{% url 'index' %}"
                       class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">
                        <i class="fa-solid fa-house-laptop"></i>
                        主页
                    </a>
                </li>
                <li>
                    <a href="{% url 'television:index' %}"
                       class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">
                        <i class="fa-solid fa-tv"></i>
                        电视
                    </a>
                </li>
                {% if user.is_authenticated %}
                    <li>
                        <button id="dropdownNavbarLink" data-dropdown-toggle="dropdownNavbar"
                                class="flex gap-2 items-center justify-between w-full py-2 px-3 text-gray-900 hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 md:w-auto dark:text-white md:dark:hover:text-blue-500 dark:focus:text-white dark:hover:bg-gray-700 md:dark:hover:bg-transparent">
                            {% if user.profile.full_name %}
                                {{ user.profile.full_name }}
                            {% else %}
                                {{ user.username }}
                            {% endif %}
                            <i class="fa-solid fa-chevron-down"></i>
                        </button>
                        <div id="dropdownNavbar"
                             class="z-10 hidden font-normal bg-white divide-y divide-gray-100 rounded-lg shadow w-44 dark:bg-gray-700 dark:divide-gray-600">
                            <ul class="py-2 text-sm text-gray-700 dark:text-gray-200"
                                aria-labelledby="dropdownLargeButton">
                                <li>
                                    <a href="{% url 'account:index' %}"
                                       class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">
                                        个人中心
                                    </a>
                                </li>
                            </ul>
                            <div class="py-1">
                                <a href="{% url 'account:logout' %}"
                                   class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white">
                                    注销
                                </a>
                            </div>
                        </div>
                    </li>
                {% else %}
                    <li>
                        <a href="{% url 'account:login' %}"
                           class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">
                            登录</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

src/templates/components/menu_link.html
{% load menu_tags %}

<a href="{{ url }}"
   class="{% nav_menu_class url %}" {% nav_menu_aria url %}>
    {{ name }}
</a>