src/apps/television/urls.py
from django.urls import path
from . import views

app_name = 'television'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/video', views.video, name='video'),
]

src/config/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.home.views import index

from config.apis import api

urlpatterns = [
    path('', index, name='index'),
    path('api/', api.urls),
    path('accounts/', include('apps.account.urls')),
    path('demo/', include('apps.demo.urls')),
    path('home/', include('apps.home.urls')),
    path('tv/', include('apps.television.urls')),

    # DjangoStarter
    path('django-starter/', include('django_starter.urls')),

    # 管理后台
    path('admin/', include('django_starter.contrib.admin.urls')),  # 实现 admin 登录验证码
    path('admin/', admin.site.urls),

    # 验证码
    path('captcha/', include('captcha.urls')),
]

src/apps/television/models.py
from django.db import models
from django_starter.db.models import ModelExt


class TvProgram(ModelExt):
    class Status(models.TextChoices):
        UPDATED = 'updated', '已更新'
        PENDING_UPDATE = 'pending_update', '待更新'
        SCRAPING = 'scraping', '采集中'
        DOWNLOADING = 'downloading', '下载中'
        FAILED = 'failed', '下载失败'

    name = models.CharField('节目名称', max_length=100)
    logo = models.ImageField('节目Logo', upload_to='tv/program/logos', null=True, blank=True)
    status = models.CharField(
        '状态', max_length=20,
        help_text='用于记录节目的当前状态，便于管理和调度。',
        choices=Status.choices,
        default=Status.PENDING_UPDATE,
    )
    source_url = models.URLField(
        '节目来源URL', null=True, blank=True,
        help_text='节目的数据来源网址，以便于爬虫程序获取更新。'
    )
    first_detected_update_time = models.DateTimeField(
        '节目更新时间', null=True, blank=True,
        help_text='节目在官网或订阅源网站上首次检测到更新的时间。'
    )
    last_synced_time = models.DateTimeField(
        '上次同步时间', null=True, blank=True,
        help_text='爬虫程序上一次去视频发布源检索节目的时间。'
    )
    local_update_time = models.DateTimeField(
        '本地更新时间', null=True, blank=True,
        help_text='节目最新的视频文件下载到本地的时间。'
    )

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'tv_program'
        verbose_name = '电视节目'
        verbose_name_plural = verbose_name


class Video(ModelExt):
    program = models.ForeignKey(
        'TvProgram', related_name='videos', verbose_name='电视节目',
        db_constraint=False, on_delete=models.CASCADE
    )
    name = models.CharField('视频名称', max_length=200)
    time = models.DateTimeField('时间', null=True, blank=True)
    related_link = models.URLField('相关链接', null=True, blank=True)
    origin_link = models.URLField('来源链接', null=True, blank=True)
    cover_link = models.URLField('封面图片链接', null=True, blank=True)
    cover = models.ImageField('视频封面', upload_to='tv/video/covers', null=True, blank=True)
    video_link = models.URLField('视频链接', null=True, blank=True)
    video = models.FileField('视频文件', upload_to='tv/video/raw-videos', null=True, blank=True)
    duration = models.DurationField('视频时长', null=True, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'tv_video'
        verbose_name = '视频'
        verbose_name_plural = verbose_name

src/apps/television/views.py
from collections import defaultdict

from django.contrib.auth.decorators import login_required
from django.db.models import Prefetch
from django.shortcuts import render, get_object_or_404
from .models import TvProgram, Video


def index(request):
    ctx = {
        'tv_programs': TvProgram.objects.all(),
    }
    return render(request, 'television/index.html', ctx)


@login_required()
def detail(request, pk):
    program = get_object_or_404(TvProgram, pk=pk)
    videos = Video.objects.filter(program=program).order_by('-time')

    # 按日期分组
    grouped_videos = defaultdict(list)
    for e in videos:
        date_str = e.time.strftime('%Y-%m-%d') if e.time else '未知日期'
        grouped_videos[date_str].append(e)

    ctx = {
        'program': program,
        'videos': videos,
        'grouped_videos': dict(grouped_videos),
    }

    return render(request, 'television/detail.html', ctx)


def video(request, pk):
    item = get_object_or_404(Video.objects.select_related('program'), pk=pk)
    # 获取与当前视频相同日期的其他视频
    same_date_videos = Video.objects.filter(
        program=item.program,
        time__date=item.time.date()
    )

    ctx = {
        'video': item,
        'same_date_videos': same_date_videos,
    }

    return render(request, 'television/video.html', ctx)

src/apps/television/templates/television/detail.html
{% extends '_base.html' %}

{% block title %}视频列表{% endblock %}

{% block content %}
    {# Breadcrumb #}
    <nav class="flex px-4 lg:px-0" aria-label="Breadcrumb">
        <ol class="inline-flex items-center space-x-1 md:space-x-2 rtl:space-x-reverse">
            <li class="inline-flex items-center">
                <a href="{% url 'index' %}"
                   class="inline-flex gap-1 items-center text-sm font-medium text-gray-600 hover:text-blue-600 dark:text-gray-400 dark:hover:text-white">
                    <i class="fa-solid fa-house-chimney"></i>
                    主页
                </a>
            </li>
            <li>
                <div class="flex items-center">
                    <i class="fa-solid fa-chevron-right"></i>
                    <a href="{% url 'television:index' %}"
                       class="ms-1 text-sm font-medium text-gray-600 hover:text-blue-600 md:ms-2 dark:text-gray-400 dark:hover:text-white">
                        电视
                    </a>
                </div>
            </li>
            <li aria-current="page">
                <div class="flex items-center">
                    <i class="fa-solid fa-chevron-right"></i>
                    <span class="ms-1 text-sm font-medium text-amber-700 md:ms-2 dark:text-gray-400">
                        {{ program.name }}
                    </span>
                </div>
            </li>
        </ol>
    </nav>

    <div class="grid sm:grid-cols-2 md:grid-cols-4 lg:grid-cols-12 gap-4 my-4 px-4 lg:px-0">
        <div class="hidden lg:col-span-3 xl:col-span-2 lg:flex justify-center items-center">
            <div class="col-span-2">
                <img class="w-64 rounded-lg" src="{{ program.logo.url }}"
                 alt="{{ program.name }}">
            </div>
        </div>

        <div class="md:col-span-2 lg:col-span-3 xl:col-span-2 flex flex-col justify-between p-6 bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700">
            <div>
                <i class="fa-solid fa-video text-4xl text-gray-500 dark:text-gray-400 mb-4"></i>
                <h5 class="mb-2 text-2xl font-semibold tracking-tight text-gray-900 dark:text-white">
                    {{ program.name }}
                </h5>
                <p class="font-normal text-gray-500 dark:text-gray-400">
                    视频数量：{{ videos|length }}
                </p>
            </div>
            <a href="{{ program.source_url }}"
               class="inline-flex gap-2 font-medium items-center text-blue-600 hover:underline">
                节目数据来源网址
                <i class="fa-solid fa-arrow-up-right-from-square rtl:rotate-[270deg]"></i>
            </a>
        </div>

        <div class="md:col-span-2 lg:col-span-6 xl:col-span-8 grid gap-4 lg:gap-8 w-full md:grid-cols-2">
            <div class="relative p-6 rounded-2xl bg-white shadow dark:bg-gray-800">
                <div class="space-y-2">
                    <div class="flex items-center space-x-2 rtl:space-x-reverse text-sm font-medium text-gray-500 dark:text-gray-200">
                        <span>状态</span>
                    </div>
                    <div class="text-3xl">{{ program.get_status_display }}</div>
                </div>
            </div>
            <div class="relative p-6 rounded-2xl bg-white shadow dark:bg-gray-800">
                <div class="space-y-2">
                    <div class="flex items-center space-x-2 rtl:space-x-reverse text-sm font-medium text-gray-500 dark:text-gray-200">
                        <span>更新时间</span>
                    </div>
                    <div class="text-3xl">{{ program.first_detected_update_time }}</div>
                </div>
            </div>

            <div class="relative p-6 rounded-2xl bg-white shadow dark:bg-gray-800">
                <div class="space-y-2">
                    <div class="flex items-center space-x-2 rtl:space-x-reverse text-sm font-medium text-gray-500 dark:text-gray-200">
                        <span>上次同步</span>
                    </div>
                    <div class="text-3xl">{{ program.last_synced_time }}</div>
                </div>
            </div>

            <div class="relative p-6 rounded-2xl bg-white shadow dark:bg-gray-800">
                <div class="space-y-2">
                    <div class="flex items-center space-x-2 rtl:space-x-reverse text-sm font-medium text-gray-500 dark:text-gray-200">
                        <span>本地更新</span>
                    </div>
                    <div class="text-3xl">{{ program.local_update_time }}</div>
                </div>
            </div>
        </div>

    </div>

    {% if grouped_videos|length > 0 %}
        {% for date, videos in grouped_videos.items %}
            <h1 class="px-4 lg:px-0 my-4 text-xl md:text-2xl lg:text-3xl font-normal leading-none tracking-tight text-gray-900 dark:text-white">
                <span class="underline underline-offset-3 decoration-8 decoration-blue-400 dark:decoration-blue-600">{{ date }}</span>
                <span class="text-md font-thin">{{ videos|length }}个视频</span>
            </h1>

            <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5 gap-4 px-4 py-4 lg:px-0">
                {% for video in videos %}
                    <a href="{% url 'television:video' video.id %}"
                       class="group cursor-pointer relative">
                        <img src="{{ video.cover_link }}"
                             alt="{{ video.name }}"
                             class="w-full h-48 object-cover rounded-lg
                             transition-transform transform scale-100 group-hover:scale-105 group-hover:blur-sm"
                        />
                        <div class="absolute inset-0 flex flex-col items-center justify-center p-4
                        rounded-lg transform scale-100 group-hover:scale-105
                        opacity-0 group-hover:opacity-60 transition-opacity group-hover:bg-gray-800 text-gray-800 group-hover:text-white">
                            <div class="text-sm my-4">{{ video.name }}</div>
                            <button class="px-3 py-1 rounded-lg bg-gray-200 text-gray-800 hover:bg-gray-600 hover:text-white transition-colors">
                                观看
                            </button>
                        </div>
                    </a>
                {% endfor %}
            </div>
        {% endfor %}
    {% else %}
        {% include 'television/components/empty_view.html' with title='这个节目还没视频哦' %}
    {% endif %}
{% endblock %}

src/apps/television/templates/television/index.html
{% extends '_base.html' %}

{% block title %}电视节目{% endblock %}

{% block content %}
    <h1 class="text-3xl text-green-800">电视节目</h1>
    {# Breadcrumb #}
    <nav class="flex py-4 px-4 lg:px-0" aria-label="Breadcrumb">
        <ol class="inline-flex items-center space-x-1 md:space-x-2 rtl:space-x-reverse">
            <li class="inline-flex items-center">
                <a href="{% url 'index' %}"
                   class="inline-flex gap-1 items-center text-sm font-medium text-gray-600 hover:text-blue-600 dark:text-gray-400 dark:hover:text-white">
                    <i class="fa-solid fa-house-chimney"></i>
                    主页
                </a>
            </li>
            <li aria-current="page">
                <div class="flex items-center">
                    <i class="fa-solid fa-chevron-right"></i>
                    <span class="ms-1 text-sm font-medium text-amber-700 md:ms-2 dark:text-gray-400">
                        电视
                    </span>
                </div>
            </li>
        </ol>
    </nav>

    {% if tv_programs|length > 0 %}
        <div class="flex flex-wrap gap-2">
            {% for program in tv_programs %}
                {% include 'television/components/tv_program_card.html' %}
            {% endfor %}
        </div>
    {% else %}
        {% include 'television/components/empty_view.html' with title='还没节目啊！事已至此，先吃饭吧？' %}
    {% endif %}
{% endblock %}

src/apps/television/templates/television/video.html
{% extends '_base.html' %}

{% load static %}

{% block title %}视频{% endblock %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'lib/plyr/dist/plyr.css' %}">
{% endblock %}

{% block content %}
    <div class="grid md:grid-cols-2 lg:grid-cols-12 justify-center items-start gap-8 px-4 lg:px-0" id="video-container">
        <div class="lg:col-span-8">
            <h1 class="py-4 text-xl font-extrabold text-gray-900 dark:text-white md:text-2xl lg:text-3xl">
                <span class="text-transparent bg-clip-text bg-gradient-to-r to-emerald-600 from-sky-400">{{ video.program.name }}</span>
                {{ video.name }}
            </h1>

            <div class="flex flex-wrap justify-between items-center mb-2">
                {# Breadcrumb #}
                <nav class="flex" aria-label="Breadcrumb">
                    <ol class="inline-flex items-center space-x-1 md:space-x-2 rtl:space-x-reverse">
                        <li class="inline-flex items-center">
                            <a href="{% url 'index' %}"
                               class="inline-flex gap-1 items-center text-sm font-medium text-gray-600 hover:text-blue-600 dark:text-gray-400 dark:hover:text-white">
                                <i class="fa-solid fa-house-chimney"></i>
                                主页
                            </a>
                        </li>
                        <li>
                            <div class="flex items-center">
                                <i class="fa-solid fa-chevron-right"></i>
                                <a href="{% url 'television:index' %}"
                                   class="ms-1 text-sm font-medium text-gray-600 hover:text-blue-600 md:ms-2 dark:text-gray-400 dark:hover:text-white">
                                    电视
                                </a>
                            </div>
                        </li>
                        <li>
                            <div class="flex items-center">
                                <i class="fa-solid fa-chevron-right"></i>
                                <a href="{% url 'television:detail' video.program.id %}"
                                   class="ms-1 text-sm font-medium text-gray-600 hover:text-blue-600 md:ms-2 dark:text-gray-400 dark:hover:text-white">
                                    {{ video.program.name }}
                                </a>
                            </div>
                        </li>
                        <li aria-current="page">
                            <div class="flex items-center">
                                <i class="fa-solid fa-chevron-right"></i>
                                <span class="ms-1 text-sm font-medium text-amber-700 md:ms-2 dark:text-gray-400">
                        视频播放
                    </span>
                            </div>
                        </li>
                    </ol>
                </nav>

                <div class="flex gap-3 text-sm text-gray-500">
                    <div class="flex gap-2 items-center">
                        <i class="fa-brands fa-youtube"></i>
                        999
                    </div>
                    <div class="flex gap-2 items-center">
                        <i class="fa-regular fa-closed-captioning"></i>
                        999
                    </div>
                    <div class="flex gap-2 items-center">
                        <i class="fa-regular fa-calendar-days"></i>
                        {{ video.time|date:'Y-m-d' }}
                    </div>
                </div>
            </div>

            <video id="player" class="border border-gray-200 rounded-lg dark:border-gray-700"
                   playsinline controls data-poster="{{ video.cover_link }}">
                <source src="{{ video.video_link }}" type="video/mp4"/>
            </video>
            
            {# 视频底部点赞、投币 #}
            <div class="flex gap-8 items-center py-4 border-b">
                <div class="flex flex-wrap gap-3 items-center">
                    <i class="fa-solid fa-thumbs-up text-4xl text-gray-500"></i>
                    <span class="text-md text-gray-500">点赞</span>
                </div>
                <div class="flex flex-wrap gap-3 items-center">
                    <i class="fa-brands fa-bitcoin text-4xl text-gray-500"></i>
                    <span class="text-md text-gray-500">投币</span>
                </div>
                <div class="flex flex-wrap gap-3 items-center">
                    <i class="fa-solid fa-star text-4xl text-gray-500"></i>
                    <span class="text-md text-gray-500">收藏</span>
                </div>
                <div class="flex flex-wrap gap-3 items-center">
                    <i class="fa-solid fa-share text-4xl text-gray-500"></i>
                    <span class="text-md text-gray-500">分享</span>
                </div>
            </div>

            <p class="text-sm font-normal text-gray-500 lg:text-lg dark:text-gray-400 my-4">{% lorem %}</p>
        </div>

        <div class="lg:col-span-4">
            {# 头像啥的 #}
            <div class="flex gap-2 justify-start items-center">
                <img class="w-20 h-20 p-1 rounded-full ring-2 ring-gray-300 dark:ring-gray-500"
                     src="{{ video.program.logo.url }}" alt="Bordered avatar">
                <div>
                    <a href="{% url 'television:detail' video.program.id %}"
                       class="font-medium text-2xl text-black dark:text-blue-500 hover:underline">
                        {{ video.program.name }}
                    </a>
                    <p class="text-gray-500">更新时间：{{ video.program.first_detected_update_time }}</p>
                </div>
            </div>
            {# 视频选集 #}
            <div class="bg-gray-100 mt-4 p-2 shadow-md rounded-lg overflow-hidden">
                <div class="flex justify-between items-center border-b px-2 py-4">
                    <div class="text-black">
                        视频选集
                        <span class="text-gray-500">(1/{{ same_date_videos|length }})</span>
                    </div>
                    <label class="inline-flex gap-2 items-center cursor-pointer">
                        <span class="text-gray-500 dark:text-gray-300">自动连播</span>
                        <input type="checkbox" value="" class="sr-only peer">
                        <div class="relative w-11 h-6 bg-gray-200 peer-focus:outline-none peer-focus:ring-4 peer-focus:ring-blue-300 dark:peer-focus:ring-blue-800 rounded-full peer dark:bg-gray-700 peer-checked:after:translate-x-full rtl:peer-checked:after:-translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:start-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all dark:border-gray-600 peer-checked:bg-blue-600"></div>
                    </label>
                </div>
                <div>
                    {% for item in same_date_videos %}
                        {% if item.id == video.id %}
                            <a href="#"
                               class="flex flex-wrap gap-2 justify-between items-center my-2 px-4 py-2 rounded-xl text-blue-500 bg-white">
                                <div class="flex gap-3 items-center">
                                    <i class="fa-brands fa-youtube font-medium"></i>
                                    <span class="text-sm">{{ item.name }}</span>
                                </div>
                                <span class="text-sm">{{ item.duration }}</span>
                            </a>
                        {% else %}
                            <a href="{% url 'television:video' item.id %}"
                               class="flex flex-wrap gap-2 justify-between items-center my-2 px-4 py-2 rounded-xl text-gray-600
                                  hover:bg-white hover:text-gray-600">
                                <div class="flex gap-3 items-center">
                                    <i class="fa-solid fa-film"></i>
                                    <span class="text-sm">{{ item.name }}</span>
                                </div>
                                <span class="text-sm">{{ item.duration }}</span>
                            </a>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
            {# 相关视频 #}
            <div class="py-4 flex flex-col gap-2">
                {% for item in same_date_videos %}
                    <div class="flex gap-2 items-center">
                        <img class="rounded-lg w-40"
                             src="{{ item.cover_link }}" alt="">
                        <div class="flex flex-col gap-1">
                            <p>{{ item.name }}</p>
                            <div class="flex gap-2 items-center text-gray-500">
                                <i class="fa-solid fa-film"></i>
                                <span class="text-sm">今日视线</span>
                            </div>
                            <div class="flex gap-4 items-center text-sm text-gray-500">
                                <div class="flex gap-2 items-center">
                                    <i class="fa-solid fa-play"></i>
                                    <span class="">666</span>
                                </div>
                                <div class="flex gap-2 items-center">
                                    <i class="fa-regular fa-comments"></i>
                                    <span class="">666</span>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

{% block extra_js %}
    <script src="{% static 'lib/plyr/dist/plyr.min.mjs' %}"></script>
    <script>
        const player = new Plyr('#player');
    </script>
{% endblock %}